# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spork-TKSlide
version:      0.09
version_from: lib/Spork/TKSlide.pm
installdirs:  site
requires:
    Spork:                         0.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
